version: '2'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    links:
      - kafka
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      # KAFKA_ADVERTISED_HOST_NAME: 192.168.15.2
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock